### ISSUE TITLE
lr_get_spec values all NAs

### ISSUE THREAD

**Issue by itamshab** [ropensci/lightr#30]
I'm trying to convert multiple .csv files to a matrix for downstream analysis, using lr_get_spec, however all values are returned NAs. 

Script used
`spec <- lr_get_spec( 
  where = getwd(),
  ext = "csv",
  lim = c(450,4500),
  sep = ",",
  subdir = FALSE,
  subdir.names = FALSE,
  ignore.case = TRUE,
  interpolate = TRUE
)`

Attaching zip of .csv files.
[a4_bulk(12).zip](https://github.com/ropensci/lightr/files/5469444/a4_bulk.12.zip)

Thanks!

**Comment by Bisaloo** [comment]
Thank you very much for the report! It should be now fixed.

You can install the development version with the fix by running:

```r
install.packages("lightr", repos = "https://dev.ropensci.org")
```

The problem was that the data in your file is stored with decreasing wavelengths where all the example I had until now have increasing wavelengths. So I didn't take this case into account. Out of curiosity where does this data come from? Do you have raw files from your spectrometer or does it only return csv?

**Comment by itamshab** [comment]
Hi Hugo,

Thanks for the fix, I will try it later today. The data comes from a Bruker
Vertex70 as OPUS files. Exporting to a shareable version is painful: I
convert to csv using the Spectragtyph software, and use R to remove rows
with text and save back as individual files. Then I call lr_get_spec to
create a matrix that I analyze with e.g. the *pls* package.
If you know a better solution, please let me know!

Best,
Itamar

**Comment by Bisaloo** [comment]
It does sound painful indeed. I don't know a better way right now since I'm not familiar with this format but if you can send me an example OPUS file, I can try to add a parser in lightr. Then you would be able to run `lr_get_spec()` directly on these files. This is precisely the use case I have in mind for lightr.

**Comment by itamshab** [comment]
That would be excellent! Here are a couple of OPUS files. Let me know if
you need extra info.

**Comment by Bisaloo** [comment]
@itamshab I didn't receive the attached files. I think you need to connect on GitHub (and not answer by email) to share them.

Alternatively, you can send them at the email address listed here: https://www.normalesup.org/~hgruson/contact.html

**Comment by Bisaloo** [comment]
FYI, the request to parse OPUS files is now tracked in #31. I'll try to get on it soon.
