### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by maelle** [ropensci/lightr#46]
:wave: here! I see failing tests via https://ropensci.r-universe.dev/ui#builds=

Is any help needed?

**Comment by Bisaloo** [comment]
:wave: thanks for the report! Here's what happened:

I disabled a feature added a couple of versions ago because I'm now not so sure it works as expected. I just forgot to disable the related test. I didn't act on it just yet because I was hoping it would be a quick check but it looks like it's going to take more time than what I'd have hoped. I fixed it in 9cf126f458dd1f4e0fac8a3ca99b6118cba5b7d1.

**Comment by maelle** [comment]
Thank you for the explanation!
